import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full bg-black text-white py-10 px-20 rounded-2xl border shadow-2xl flex items-center justify-around">
          <Link href={'/'}>
          <h1 className="text-3xl">
            Mero Notes 
          </h1>
          </Link>
          <div>
            <Link href={'/add'} className="px-10 py-3 bg-white text-black " >Add Notes</Link>
          </div>

        </header>

        <main>
        {children}
        </main>
      
      </body>
    </html>
  );
}
